name: Download and Update
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * */12 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Check for new crimes
      run: |-
        python 'python/downloader.py'
    - name: Commit and push changes
      run: |-
        git diff
        git config --global user.email "downloader-bot@example.com"
        git config --global user.name "download-bot"
        git diff --quiet || (git add -A && git commit -m "Updated with latest")
        git push
    - name: Update Feed and Page
      run: |-
        python 'python/content.py'
    - name: Commit and push changes
      run: |-
        git diff
        git config --global user.email "content-bot@example.com"
        git config --global user.name "content-bot"
        git diff --quiet || (git add -A && git commit -m "Updated with latest")
        git push
